flowchart TD
    A([Início]) --> B[ler limite <- 5]
    B --> C[/receber n_tentativas/]
    C --> D{n_tentativas < limite?}
    D --> E[/Mostrar restantes/]
    E -- Sim --> F[restantes <- limite - n_tentativas]
    D -- Não --> G[/Conta Bloqueada/]
        
    F --> H([Fim])
    G --> H([Fim])
    