%% Pretendemos documentar o processo de cálculo do total de uma compra de N artigos iguais (ie,
%% com o mesmo preço).  Começa-se por obter/ler o preço do artigo, o número de artigos e um
%% imposto fnal a aplicar. O imposto é introduzido em percentagem. No fnal, exibe-se o preço
%% total com o imposto aplicado bem como o montante de imposto. Note que entre a leitura dos
%% valores de entrada e a exibição dos resultados, poderá ser conveniente obter alguns cálculos
%% intermédios (por exemplo, o preço total sem imposto).

flowchart
A([Início]) --> B[/Ler €/]
B --> C[/Qtd/]
C --> D[/Taxa_Imposto/]
D --> E[V_Compra <- € * Qtd]
E --> F[V_Imposto <- V_Compra * Imposto]
F --> G[Montante_com_Imposto <- V_compra + V_imposto]
G --> H[/Mostrar Valor_Compra/]
H --> I[/Mostrar Montante_com_Imposto/]
I --> J([Fim])
